# Generated by Django 6.0.4 on 2026-04-18 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('الملز', 'الملز'), ('العليا', 'العليا'), ('المعذر', 'المعذر'), ('البطحاء', 'البطحاء'), ('الشميسي', 'الشميسي')], max_length=100, verbose_name='المنطقة')),
                ('site_type', models.CharField(blank=True, choices=[('مواقع', 'مواقع'), ('دورات مياه', 'دورات مياه'), ('مساحات انتشارية', 'مساحات انتشارية')], max_length=100, null=True, verbose_name='نوع الموقع')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
            },
        ),
        migrations.CreateModel(
            name='ReportItemEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500, verbose_name='اسم البند الفني')),
                ('status', models.CharField(max_length=255, verbose_name='الحالة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'سجل التقارير التفصيلي',
                'verbose_name_plural': 'سجل التقارير التفصيلي (جدول مدمج)',
            },
        ),
    ]
