# Generated by Django 6.0.4 on 2026-04-19 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('الملز', 'الملز'), ('العليا', 'العليا'), ('المعذر', 'المعذر'), ('البطحاء', 'البطحاء'), ('الشميسي', 'الشميسي')], max_length=100, verbose_name='الوحدة')),
                ('site_type', models.CharField(choices=[('مواقع', 'مواقع'), ('دورات مياه', 'دورات مياه'), ('مساحات انتشارية', 'مساحات انتشارية')], max_length=100, verbose_name='نوع الموقع')),
                ('name', models.CharField(max_length=500, verbose_name='اسم الموقع')),
            ],
            options={
                'verbose_name': 'موقع ميداني',
                'verbose_name_plural': 'المواقع الميدانية',
                'ordering': ['region', 'site_type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(choices=[('الملز', 'الملز'), ('العليا', 'العليا'), ('المعذر', 'المعذر'), ('البطحاء', 'البطحاء'), ('الشميسي', 'الشميسي')], max_length=100, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='القائم بالزيارة'),
        ),
    ]
