# Generated by Django 6.0.4 on 2026-04-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitelocation_alter_report_region_alter_report_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelocation',
            options={'verbose_name': 'موقع', 'verbose_name_plural': 'المواقع'},
        ),
        migrations.AddField(
            model_name='sitelocation',
            name='parent_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sitelocation', verbose_name='الموقع الأب (لحذفهما معاً)'),
        ),
    ]
