# Generated by Django 6.0.4 on 2026-04-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitelocation_options_sitelocation_parent_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitelocation',
            name='parent_site',
        ),
    ]
