# Generated by Django 6.0.4 on 2026-04-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitelocation_parent_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteLocation',
            new_name='Location',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'region', 'site_type')},
        ),
    ]
